services:
    marttiphpbb.menuitems.console.generate:
        class: marttiphpbb\menuitems\console\generate
        arguments:
            - '@user'
        tags:
            - { name: console.command }

    marttiphpbb.menuitems.listener:
        class: marttiphpbb\menuitems\event\listener
        arguments:
            - '@marttiphpbb.menuitems.service.menuitems_dispatcher'
            - '@marttiphpbb.menuitems.service.menuitems_store'
            - '@marttiphpbb.menuitems.acp'
        tags:
            - { name: event.listener }

    marttiphpbb.menuitems.service.menuitems_dispatcher:
        class: marttiphpbb\menuitems\service\menuitems_dispatcher
        arguments:
            - '@dispatcher'
            - '@marttiphpbb.menuitems.service.menuitems_store'

    marttiphpbb.menuitems.service.menuitems_store:
        class: marttiphpbb\menuitems\service\menuitems_store
        arguments:
            - '@config_text'
            - '@cache.driver'

    marttiphpbb.menuitems.acp:
        class: marttiphpbb\menuitems\service\acp
        arguments:
            - '@marttiphpbb.menuitems.service.menuitems_store'
            - '@request'
            - '@language'