services:
    marttiphpbb.menuitems.listener:
        class: marttiphpbb\menuitems\event\listener
        arguments:
            - '@marttiphpbb.menuitems.service.links'
        tags:
            - { name: event.listener }

    marttiphpbb.menuitems.render.links:
        class: marttiphpbb\menuitems\render\links
        arguments:
            - '@config'
            - '@template'
            - '@language'

    marttiphpbb.menuitems.service.menuitems_dispatcher:
        class: marttiphpbb\menuitems\service\menuitems_dispatcher
        arguments:
            - '@dispatcher'
            - '@marttiphpbb.menuitems.service.menuitems_cache'

    marttiphpbb.menuitems.service.menuitems_cache:
        class: marttiphpbb\menuitems\service\menuitems_cache
        arguments:
            - '@cache.driver'
            - '@config_text'