services:
    marttiphpbb.menuitems.console.generate:
        class: marttiphpbb\menuitems\console\generate
        arguments:
            - '@user'
        tags:
            - { name: console.command }

    marttiphpbb.menuitems.listener:
        class: marttiphpbb\menuitems\event\listener
        arguments:
            - '@marttiphpbb.menuitems.dispatcher'
            - '@marttiphpbb.menuitems.store'
            - '@marttiphpbb.menuitems.acp'
        tags:
            - { name: event.listener }

    marttiphpbb.menuitems.dispatcher:
        class: marttiphpbb\menuitems\service\dispatcher
        arguments:
            - '@dispatcher'
            - '@marttiphpbb.menuitems.store'

    marttiphpbb.menuitems.store:
        class: marttiphpbb\menuitems\service\store
        arguments:
            - '@config_text'
            - '@cache.driver'

    marttiphpbb.menuitems.acp:
        class: marttiphpbb\menuitems\service\acp
        arguments:
            - '@marttiphpbb.menuitems.store'
            - '@request'
            - '@language'