services:
    marttiphpbb.menulinks.listener:
        class: marttiphpbb\menulinks\event\listener
        arguments:
            - '@marttiphpbb.menulinks.service.links'
        tags:
            - { name: event.listener }

    marttiphpbb.menulinks.render.links:
        class: marttiphpbb\menulinks\render\links
        arguments:
            - '@config'
            - '@template'
            - '@language'

    marttiphpbb.menulinks.service.links:
        class: marttiphpbb\menulinks\service\links
        arguments:
            - '@dispatcher'