services:
    marttiphpbb.menulinks.main_listener:
        class: marttiphpbb\menulinks\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@marttiphpbb.menulinks.render.links'
        tags:
            - { name: event.listener }

    marttiphpbb.menulinks.render.links:
        class: marttiphpbb\menulinks\render\links
        arguments:
            - '@config'
            - '@template'
            - '@language'
